-- MySQL Script generated by MySQL Workbench
-- Sun 30 Oct 2016 11:53:05 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS fibbage;
CREATE DATABASE fibbage;
USE fibbage;


-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS Question;
CREATE TABLE `Question` (
  `id` INT NOT NULL,
  `question` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))



